export class InputManager {
  constructor(root){this.root=root;this.players=[this.state(),this.state()];this.keys=new Set();this.bind()}
  state(){return{x:0,y:0,dash:false,dashQueued:false,itemQueued:false,joyPointer:null,dashPointer:null,itemPointer:null}}
  bind(){
    this.root.querySelectorAll('[data-joystick]').forEach(el=>{const p=+el.dataset.joystick;el.addEventListener('pointerdown',e=>this.joyDown(e,el,p));el.addEventListener('pointermove',e=>this.joyMove(e,el,p));['pointerup','pointercancel','lostpointercapture'].forEach(t=>el.addEventListener(t,e=>this.joyUp(e,el,p)))});
    this.root.querySelectorAll('[data-dash]').forEach(el=>{const p=+el.dataset.dash;el.addEventListener('pointerdown',e=>{e.preventDefault();const s=this.players[p];if(s.dashPointer!==null)return;s.dashPointer=e.pointerId;s.dash=true;s.dashQueued=true;el.setPointerCapture?.(e.pointerId)});['pointerup','pointercancel','lostpointercapture'].forEach(t=>el.addEventListener(t,e=>{const s=this.players[p];if(s.dashPointer===e.pointerId){s.dashPointer=null;s.dash=false}}))});
    this.root.querySelectorAll('[data-item]').forEach(el=>{const p=+el.dataset.item;el.addEventListener('pointerdown',e=>{e.preventDefault();const s=this.players[p];if(s.itemPointer!==null)return;s.itemPointer=e.pointerId;s.itemQueued=true;el.setPointerCapture?.(e.pointerId)});['pointerup','pointercancel','lostpointercapture'].forEach(t=>el.addEventListener(t,e=>{const s=this.players[p];if(s.itemPointer===e.pointerId)s.itemPointer=null}))});
    addEventListener('keydown',e=>{if(['Space','Enter','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Slash'].includes(e.code))e.preventDefault();this.keys.add(e.code);if(e.code==='Space'&&!e.repeat)this.players[0].dashQueued=true;if(['Enter','ShiftRight','ShiftLeft'].includes(e.code)&&!e.repeat)this.players[1].dashQueued=true;if(e.code==='KeyQ'&&!e.repeat)this.players[0].itemQueued=true;if(['Slash','KeyP'].includes(e.code)&&!e.repeat)this.players[1].itemQueued=true},{passive:false});addEventListener('keyup',e=>this.keys.delete(e.code));addEventListener('blur',()=>{this.keys.clear();this.resetPointers()});
  }
  joyDown(e,el,p){e.preventDefault();const s=this.players[p];if(s.joyPointer!==null)return;s.joyPointer=e.pointerId;el.setPointerCapture?.(e.pointerId);this.joyMove(e,el,p)}
  joyMove(e,el,p){const s=this.players[p];if(s.joyPointer!==e.pointerId)return;const r=el.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.34,len=Math.hypot(dx,dy)||1,k=Math.min(1,max/len);s.x=dx*k/max;s.y=dy*k/max;el.firstElementChild.style.transform=`translate(${dx*k}px,${dy*k}px)`}
  joyUp(e,el,p){const s=this.players[p];if(s.joyPointer!==e.pointerId)return;s.joyPointer=null;s.x=s.y=0;el.firstElementChild.style.transform='translate(0,0)'}
  get(p){const s=this.players[p];let x=s.x,y=s.y;if(p===0){x+=(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0);y+=(this.keys.has('KeyS')?1:0)-(this.keys.has('KeyW')?1:0)}else{x+=(this.keys.has('ArrowRight')?1:0)-(this.keys.has('ArrowLeft')?1:0);y+=(this.keys.has('ArrowDown')?1:0)-(this.keys.has('ArrowUp')?1:0)}const l=Math.hypot(x,y);if(l>1){x/=l;y/=l}const dash=s.dashQueued,item=s.itemQueued;s.dashQueued=s.itemQueued=false;return{x,y,dash,item}}
  resetPointers(){this.players.forEach((s,p)=>{s.x=s.y=0;s.dash=s.dashQueued=s.itemQueued=false;s.joyPointer=s.dashPointer=s.itemPointer=null;const stick=this.root.querySelector(`[data-joystick="${p}"] .stick`);if(stick)stick.style.transform='translate(0,0)'})}
}
