import {boardPosition,createBoard} from './board.js';
import {SPECIAL_CARD_INFO,canUseBank,getAuctionBidder,getBermudaTargets,getBuildableOwnedCities,getCurrentPlayer,getPaymentPlayer,getEarlyAuctionVoter,getGlobalEffectRounds,getGhostCityTargets,getTrojanTargets,getLoanBalance,getNetWorth,getTradeableAssets,getUnownedPurchasableAssets,isGlobalEffectActive,maxBuildingLevel} from './game.js';
import {PHASES,RULES,effectiveBuildingLevel,formatMoney,hasGhostCity,regionMeta} from './rules.js';
import {activeTrojan} from './city-effects.js';
import {animateMoneyTransfer,showGamblerResult} from './animations.js';
import {EVENT_CARDS} from './data/events.js';

const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const phaseLabel={
  [PHASES.FATE_DECISION]:'운명의 갈림길 · 선택',[PHASES.FATE_ROLLING]:'도전 주사위 결과 확인',[PHASES.TROJAN_DECISION]:'트로이 목마 · 상대 도시 선택',[PHASES.GHOST_CITY_DECISION]:'유령도시 · 내 도시 선택',
  [PHASES.BERMUDA_DECISION]:'버뮤다 삼각지대 · 교환 상대 선택',
  [PHASES.WAITING_FOR_ROLL]:'주사위를 굴릴 차례',[PHASES.ROLLING]:'주사위 굴리는 중',[PHASES.MOVING]:'이동 중',[PHASES.RESOLVING_TILE]:'도착지 확인 중',
  [PHASES.BUY_DECISION]:'인수 결정',[PHASES.BUILD_DECISION]:'도시 개발',[PHASES.BUILD_ANYWHERE_DECISION]:'보유 도시 자유 건설',[PHASES.EARLY_AUCTION_VOTE]:'조기 경매 만장일치 투표',[PHASES.AUCTION]:'잔여 자산 경매',[PHASES.TRAVEL_DECISION]:'게임판에서 목적지 선택',[PHASES.WORLD_CUP_DECISION]:'월드컵 개최 도시 선택',[PHASES.TERROR_TARGET_DECISION]:'파괴할 건물이 있는 도시 선택',[PHASES.INDUSTRIALIZATION_DECISION]:'산업화할 도시 선택',[PHASES.PAYMENT_DECISION]:'통행료 지불 방법 선택',[PHASES.TRADE]:'플레이어 거래',[PHASES.ASSET_MANAGEMENT]:'자산 정리',[PHASES.END_TURN]:'턴 마무리',[PHASES.GAME_OVER]:'게임 종료',
};
const stageLabel={FIRST_HALF:'전반전 · 토지 매입',AUCTION:'하프타임 · 경매',SECOND_HALF:'후반전 · 도시 개발'};

function tilePrice(tile){return tile.purchasePrice?formatMoney(tile.purchasePrice):tile.type==='event'?'KEY CARD':tile.type==='tax'?`−${formatMoney(tile.amount)}`:tile.type.toUpperCase()}
function buildingLabel(tile,level=effectiveBuildingLevel(tile)){const landmark=tile?.landmarkName||'대표 랜드마크';return ['땅',`${landmark} 기초`,`${landmark} 건설 중`,`${landmark} 1동`,`${landmark} 2동`,`${landmark} 3동`][level]??'땅'}
function buildingMarkup(tile){
  if(tile.type!=='city'||!tile.ownerId)return '';
  const label=buildingLabel(tile);const level=effectiveBuildingLevel(tile);const ghost=hasGhostCity(tile);
  const badges=`${ghost?'<span class="temporary-city-badge ghost-badge" title="유령도시 · 임시 호텔 2개">👻 호텔 2개</span>':''}${tile.trojanHorse?.remainingTurns>0?'<span class="temporary-city-badge trojan-badge" title="트로이 목마 · 다음 통행료 수익 가로채기">🎁 목마</span>':''}`;
  if(level===0)return `${badges}<span class="tile-building-label land-label">땅</span>`;
  const landmarkCount=level<3?1:level-2;const glyph=escapeHtml(tile.landmarkGlyph||'▥');
  const stage=level===1?'기초':level===2?'건설 중':`${level-2}동`;return `${badges}<span class="city-landmark landmark-stage-${level}${ghost?' ghost-landmark':''}" role="img" aria-label="${escapeHtml(label)}${ghost?', 유령도시 임시 호텔 2개':''}" title="${escapeHtml(label)}">${`<b>${glyph}</b>`.repeat(landmarkCount)}</span><span class="tile-building-label">${escapeHtml(tile.landmarkShort||tile.landmarkName)} ${stage}</span>`;
}
function tokenMarkup(players,index){
  return `<span class="tile-tokens">${players.filter(player=>!player.bankrupt&&player.position===index).map((player,tokenIndex)=>`<i class="player-token token-${tokenIndex}" data-player-token="${player.id}" style="--token:${player.color}" title="${escapeHtml(player.name)}"><b>${player.token}</b></i>`).join('')}</span>`;
}
function tileArtwork(tile){
  return tile.imageKey?`<span class="tile-art tile-art-${tile.imageKey}" role="img" aria-label="${escapeHtml(tile.name)} 그림"></span>`:`<b class="tile-icon" aria-hidden="true">${tile.icon}</b>`;
}
function tileSide(index){
  if([0,10,20,30].includes(index))return 'corner';
  if(index<10)return 'bottom';if(index<20)return 'left';if(index<30)return 'top';return 'right';
}
function boardMarkup(state){
  const board=state?.board??createBoard();const players=state?.players??[];const imperialActive=state&&isGlobalEffectActive(state,'imperialExploitation');const rageActive=state&&isGlobalEffectActive(state,'americanRage');const genevaActive=state&&isGlobalEffectActive(state,'genevaConvention');const koreanTiles=new Set(['jeju','busan','seoul-olympic']);
  return `<div class="board-grid">${board.map((tile,index)=>{
    const position=boardPosition(index);const region=regionMeta(tile.region);const owner=state?.players.find(player=>player.id===tile.ownerId);
    const side=tileSide(index);const travelTarget=state?.phase===PHASES.TRAVEL_DECISION&&tile.type==='city';const terrorTarget=state?.phase===PHASES.TERROR_TARGET_DECISION&&tile.type==='city'&&effectiveBuildingLevel(tile)>0;const industrialTarget=state?.phase===PHASES.INDUSTRIALIZATION_DECISION&&tile.type==='city'&&tile.ownerId===getCurrentPlayer(state).id&&tile.buildable!==false&&!hasGhostCity(tile)&&tile.buildingLevel<RULES.INDUSTRIALIZED_MAX_BUILDING_LEVEL;const auctionTarget=state?.phase===PHASES.AUCTION&&tile.id===state.auction?.currentTileId;const occupationTarget=imperialActive&&koreanTiles.has(tile.id);const transportLocked=rageActive&&(tile.type==='facility'||tile.id==='space-travel');const islandClosed=genevaActive&&tile.id==='deserted-island';
    const targetAttrs=travelTarget?` data-action="choose-space-destination" data-destination-index="${index}" role="button" tabindex="0"`:terrorTarget?` data-action="choose-terror-target" data-tile="${tile.id}" role="button" tabindex="0"`:industrialTarget?` data-action="choose-industrialization-city" data-tile="${tile.id}" role="button" tabindex="0"`:'';
    return `<article class="board-tile tile-${tile.type} side-${side}${side==='corner'?' corner':''}${tile.buildingLevel===maxBuildingLevel(tile)?' landmark':''}${tile.industrialized?' industrialized':''}${tile.worldCupTurns>0?' world-cup-host':''}${travelTarget?' travel-target':''}${terrorTarget?' terror-target':''}${industrialTarget?' industrial-target':''}${auctionTarget?' auction-target':''}${occupationTarget?' occupation-target':''}${transportLocked?' transport-locked':''}${islandClosed?' island-closed':''}" data-tile-index="${index}"${targetAttrs} style="--row:${position.row};--column:${position.column};--region:${region.color};--band:${tile.bandColor||'transparent'};--owner:${owner?.color||'transparent'}" aria-label="${escapeHtml(tile.name)}${owner?`, ${owner.name} 소유`:''}${tile.industrialized?', 산업화 도시, 통행료 수익 80% 지급, 최대 3동':''}${tile.worldCupTurns>0?`, 월드컵 통행료 2배 ${tile.worldCupTurns}차례`:''}${occupationTarget?', 일제의 수탈로 통행료 도쿄 귀속':''}${transportLocked?', 미국의 분노로 이용 금지':''}${islandClosed?', 제네바 협정으로 출입 금지':''}${auctionTarget?', 현재 경매 중':''}${travelTarget?', 우주여행 목적지로 선택':''}${terrorTarget?', 파괴 대상으로 선택':''}${industrialTarget?', 산업화 대상으로 선택':''}">
      ${tile.bandColor?'<span class="tile-band"></span>':''}<span class="owner-strip"></span>${buildingMarkup(tile)}${tile.industrialized?'<span class="industrial-badge" title="산업화 · 최대 3동 · 통행료 수익 80%">🏭 80%</span>':''}${tile.worldCupTurns>0?`<span class="world-cup-badge" title="월드컵 통행료 2배 · ${tile.worldCupTurns}차례 남음">⚽ ×2</span>`:''}${occupationTarget?'<span class="occupation-badge" title="일제의 수탈 · 통행료가 도쿄 소유주에게 귀속">🇯🇵 도쿄 귀속</span>':''}${transportLocked?'<span class="transport-lock-badge" title="미국의 분노 · 이동수단 이용 금지">⛔ 운항 중단</span>':''}${islandClosed?'<span class="island-closed-badge" title="제네바 협정 · 무인도 출입 금지">⚖ 출입 금지</span>':''}${auctionTarget?'<span class="auction-badge">경매 중</span>':''}<span class="tile-face">${tileArtwork(tile)}<strong>${escapeHtml(tile.name)}</strong><span class="tile-en">${escapeHtml(tile.englishName)}</span><small>${tilePrice(tile)}</small></span>${tokenMarkup(players,index)}
    </article>`;
  }).join('')}
    <div class="board-center">
      <span class="center-card-deck" role="img" aria-label="가운데에 쌓아 둔 황금열쇠 카드 ${state?Math.max(0,state.eventDeck.length-state.eventCursor):EVENT_CARDS.length}장">
        <i class="deck-card deck-card-back"></i><i class="deck-card deck-card-middle"></i><span class="deck-card deck-card-top"><b>◆</b><strong>황금열쇠</strong><small>GOLDEN KEY</small></span><em>${state?Math.max(0,state.eventDeck.length-state.eventCursor):EVENT_CARDS.length}장</em>
      </span>
      <span class="center-station" aria-hidden="true"><i></i><b>✦</b></span>
      <h1>WORLD<br><em>TYCOON</em></h1>
      <div class="route-orbit" aria-hidden="true"><i></i><i></i><i></i><span>✈</span></div>
      ${state?centerStatus(state):'<p class="board-tagline">세계를 돌며 도시의 가치를 키우세요</p>'}
    </div>
  </div>`;
}

function centerStatus(state){
  const player=state.phase===PHASES.EARLY_AUCTION_VOTE?getEarlyAuctionVoter(state):getCurrentPlayer(state);
  return `<div class="center-status"><span style="--token:${player.color}"><i>${player.token}</i>${escapeHtml(player.name)}</span><b>${phaseLabel[state.phase]}</b><small>${stageLabel[state.gameStage]||'게임 진행'} · TURN ${state.turnNumber}</small></div>`;
}

function modeLabel(mode){return mode==='full'?'완전 게임':`${mode}분 모드`}
function timerLabel(state){
  if(state.timer.remainingSeconds===null)return '∞';const seconds=Math.max(0,state.timer.remainingSeconds);const minutes=Math.floor(seconds/60);return `${String(minutes).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
}

function previewLayout(sidebar){return `<main class="game-layout preview-mode"><section class="board-panel" aria-label="World Tycoon 게임 보드">${boardMarkup(null)}</section>${sidebar}</main><div id="modal-root"></div>`}

export function renderStart(root,{savedGames=[],setup=false,playerCount=2,selectedSlot=1}={}){
  if(!setup){
    const slots=Array.from({length:RULES.SAVE_SLOT_COUNT},(_,index)=>{const slot=index+1;const game=savedGames[index];return `<article class="save-slot ${game?'occupied':'empty'}"><span>SAVE ${slot}</span>${game?`<h3>${escapeHtml(game.players[game.currentPlayerIndex].name)} 차례</h3><p>${stageLabel[game.gameStage]||'게임 진행'} · TURN ${game.turnNumber}</p><small>${game.players.length}명 · ${modeLabel(game.mode)} · ${timerLabel(game)}</small><button class="primary-button" type="button" data-action="continue-game" data-slot="${slot}">이어하기 <b>→</b></button><button class="secondary-button wide" type="button" data-action="new-game" data-slot="${slot}">새 게임으로 덮어쓰기</button>`:`<h3>빈 저장 슬롯</h3><p>새로운 월드 타이쿤 게임을 저장할 수 있습니다.</p><button class="primary-button" type="button" data-action="new-game" data-slot="${slot}">새 게임 시작 <b>→</b></button>`}</article>`}).join('');
    root.innerHTML=previewLayout(`<aside class="control-panel setup-card save-select-card"><p class="eyebrow">TWO SAVED JOURNEYS</p><h2>게임을 선택하세요</h2><div class="save-slot-grid">${slots}</div><button class="text-button" type="button" data-action="open-help">? 게임 방법</button></aside>`);return;
  }
  root.innerHTML=previewLayout(`<aside class="control-panel setup-card"><p class="eyebrow">SAVE ${selectedSlot} · PASS &amp; PLAY</p><h2>새로운 여행을<br>시작할까요?</h2><p class="setup-copy">전반전에는 토지만 매입하고, 잔여 5개 또는 전원 동의 시 경매 뒤 후반전부터 도시를 개발합니다.</p>
    <form data-setup-form><fieldset><legend>플레이 인원</legend><div class="choice-row">${[2,3,4].map(count=>`<button class="choice ${count===playerCount?'active':''}" type="button" data-action="choose-player-count" data-players="${count}"><b>${count}</b><span>명</span></button>`).join('')}</div></fieldset>
    <fieldset class="name-fields"><legend>플레이어 이름</legend>${[0,1,2,3].map(index=>`<label class="name-field ${index>=playerCount?'hidden':''}" data-name-field="${index}"><i style="--player-color:${['#ff5d7d','#4ed6ff','#ffd65a','#8c7bff'][index]}"></i><input name="player-${index}" maxlength="12" value="플레이어 ${index+1}" aria-label="플레이어 ${index+1} 이름"></label>`).join('')}</fieldset>
    <fieldset><legend>게임 모드</legend><div class="mode-grid">${[['full','완전 게임','마지막 1명까지'],['30','30분','빠른 여행'],['45','45분','균형 잡힌 게임'],['60','60분','여유로운 투자']].map(([value,label,copy],index)=>`<label class="mode-option"><input type="radio" name="mode" value="${value}" ${index===1?'checked':''}><span><b>${label}</b><small>${copy}</small></span></label>`).join('')}</div></fieldset>
    <button class="primary-button" type="submit">게임 시작 <span>→</span></button></form><button class="text-button" type="button" data-action="open-help">? 게임 방법</button></aside>`);
}

function die(value){
  const dots={1:[5],2:[1,9],3:[1,5,9],4:[1,3,7,9],5:[1,3,5,7,9],6:[1,3,4,6,7,9]}[value];
  return `<span class="die" aria-label="주사위 ${value}">${Array.from({length:9},(_,index)=>`<i class="${dots.includes(index+1)?'on':''}"></i>`).join('')}</span>`;
}

function playerStrip(state){
  const focusedId=state.phase===PHASES.EARLY_AUCTION_VOTE?state.earlyAuctionVote?.currentVoterId:state.players[state.currentPlayerIndex]?.id;return `<section class="player-strip" aria-label="플레이어 현황">${state.players.map(player=>`<article class="player-mini ${player.id===focusedId?'current':''} ${player.bankrupt?'bankrupt':''}" data-player-mini="${player.id}" style="--player-color:${player.color}"><i>${player.token}</i><span><b>${escapeHtml(player.name)}</b><small>${player.bankrupt?'파산':`${formatMoney(player.money)} · 자산 ${formatMoney(getNetWorth(state,player.id))}${getLoanBalance(player)?` · 대출 ${formatMoney(getLoanBalance(player))}`:''}`}</small></span></article>`).join('')}</section>`;
}

function globalEffectsPanel(state){
  const effects=[];
  for(const tile of state.board){
    if(hasGhostCity(tile))effects.push(`<article class="global-effect ghost-effect"><i>👻</i><span><b>${escapeHtml(tile.name)} · 유령도시</b><small>호텔 2개 · 남은 일반 차례 ${tile.ghostCity.remainingTurns}회 · 종료 후 ${escapeHtml(buildingLabel(tile,tile.buildingLevel))}</small></span></article>`);
    const trojan=activeTrojan(state,tile);if(trojan)effects.push(`<article class="global-effect trojan-effect"><i>🎁</i><span><b>${escapeHtml(tile.name)} · 트로이 목마</b><small>다음 통행료 수익 1회 → ${escapeHtml(state.players.find(p=>p.id===trojan.beneficiaryId).name)} · 남은 일반 차례 ${trojan.remainingTurns}회</small></span></article>`);
  }
  if(state.doubleNextEvent)effects.push('<article class="global-effect"><i>×2</i><span><b>묻고 더블로 가! 대기 중</b><small>다음 황금열쇠는 두 장 · 기한 없음</small></span></article>');
  for(const oath of state.oaths||[]){const players=oath.playerIds.map(id=>state.players.find(player=>player.id===id));if(oath.remainingTurns>0&&players.every(player=>player&&!player.bankrupt))effects.push(`<article class="global-effect oath-effect"><i>🤝</i><span><b>도원결의 · ${escapeHtml(players.map(player=>player.name).join(' ↔ '))}</b><small>수입·벌금·통행료 1/2 · 남은 일반 차례 ${oath.remainingTurns}회 (더블 제외)</small></span></article>`)}
  if(state.eventQueue?.length)effects.push(`<article class="global-effect"><i>◆</i><span><b>추가 황금열쇠 ${state.eventQueue.length}장 대기</b><small>현재 카드의 선택·정산 후 이어집니다.</small></span></article>`);
  if(state.pendingDebt?.oathShared)effects.push(`<article class="global-effect oath-effect"><i>½</i><span><b>${escapeHtml(getPaymentPlayer(state).name)}의 분담금 정산</b><small>우대권은 본인 몫만 면제합니다. 정산을 마치면 ${escapeHtml(getCurrentPlayer(state).name)}의 차례를 이어갑니다.</small></span></article>`);
  if(isGlobalEffectActive(state,'imperialExploitation')){const tokyo=state.board.find(tile=>tile.id==='tokyo');const owner=state.players.find(player=>player.id===tokyo?.ownerId&&!player.bankrupt);effects.push(`<article class="global-effect imperial-effect"><i>🇯🇵</i><span><b>일제의 수탈 · ${getGlobalEffectRounds(state,'imperialExploitation')}라운드</b><small>한국 통행료 → ${owner?`${escapeHtml(owner.name)}(도쿄 소유주)`:'도쿄 미소유 시 은행'}</small></span></article>`) }
  if(isGlobalEffectActive(state,'americanRage'))effects.push(`<article class="global-effect rage-effect"><i>⛔</i><span><b>미국의 분노 · ${getGlobalEffectRounds(state,'americanRage')}라운드</b><small>이동수단·우주여행·황금열쇠 이동 봉쇄</small></span></article>`);
  if(isGlobalEffectActive(state,'genevaConvention'))effects.push(`<article class="global-effect geneva-effect"><i>⚖</i><span><b>제네바 협정 · ${getGlobalEffectRounds(state,'genevaConvention')}라운드</b><small>무인도 출입 금지 · 갇힘 효과 무효</small></span></article>`);
  return effects.length?`<section class="global-effects" aria-label="현재 전역 효과">${effects.join('')}</section>`:'';
}

function bankPanel(state){
  if(state.phase===PHASES.GAME_OVER)return '';const player=state.phase===PHASES.AUCTION?getAuctionBidder(state):getPaymentPlayer(state);const loan=player.bankLoan;const balance=getLoanBalance(player);const remainingCapacity=RULES.BANK_LOAN_MAX-(loan?.principal||0);const available=canUseBank(state);
  if(!loan)return `<section class="bank-panel"><div class="section-label"><span>SEED BANK</span><b>₩</b></div><p class="bank-copy">최대 100만 원 · 고정 이자 10% · 3바퀴 만기</p>${remainingCapacity>=100000?`<form data-loan-form><input name="loanAmount" type="number" min="100000" max="${remainingCapacity}" step="10000" value="${Math.min(1000000,remainingCapacity)}" aria-label="은행 대출 금액"><button type="submit" ${available?'':'disabled'}>대출받기</button></form>`:''}</section>`;
  const remainingLaps=Math.max(0,loan.dueLap-player.lapsCompleted);const arc=Math.min(360,Math.max(0,remainingLaps/RULES.BANK_LOAN_TERM_LAPS*360));
  return `<section class="bank-panel loan-active"><div class="section-label"><span>SEED BANK · LOAN CLOCK</span><b>₩</b></div><div class="loan-summary"><span><small>대출 원금</small><b>${formatMoney(loan.principal)}</b></span><span><small>이자 10%</small><b>${formatMoney(loan.interest)}</b></span><div class="loan-lap-gauge ${remainingLaps<=1?'loan-urgent':''}" data-loan-player="${player.id}" data-loan-remaining="${remainingLaps}" style="--loan-arc:${arc}deg" role="img" aria-label="대출 만기까지 ${remainingLaps}바퀴"><i><b>${remainingLaps}</b><small>바퀴</small></i></div></div><div class="loan-track" aria-hidden="true"><i class="${remainingLaps<=2?'passed':''}">3</i><span></span><i class="${remainingLaps<=1?'passed':''}">2</i><span></span><i class="${remainingLaps<=0?'passed':''}">1</i></div><button class="bank-repay-button" type="button" data-action="repay-bank-loan" ${!available||player.money<balance?'disabled':''}>전액 상환 ${formatMoney(balance)}</button>${remainingCapacity>=100000?`<form data-loan-form><input name="loanAmount" type="number" min="100000" max="${remainingCapacity}" step="10000" value="${Math.min(1000000,remainingCapacity)}" aria-label="은행 추가 대출 금액"><button type="submit" ${available?'':'disabled'}>추가 대출</button></form>`:''}</section>`;
}

function decisionPanel(state){
  const player=state.phase===PHASES.EARLY_AUCTION_VOTE?getEarlyAuctionVoter(state):getPaymentPlayer(state);const tile=state.pendingAction?state.board[state.pendingAction.tileIndex]:state.board[player.position];
  if(state.phase===PHASES.FATE_DECISION)return `<div class="fate-decision"><span class="action-kicker">FATEFUL CROSSROADS</span><h3>안전하게, 아니면 도전?</h3><p>도전은 주사위 한 개로 결정합니다. 이동·더블·라스베가스 효과와는 별개이며 도원결의는 적용됩니다.</p><button type="button" class="fate-choice safe" data-action="choose-fate" data-choice="safe"><b>안전하게 받기</b><strong>+15만 원</strong><small>확정 수입</small></button><button type="button" class="fate-choice risk" data-action="choose-fate" data-choice="risk"><b>운명에 도전 🎲</b><strong>1~3: −20만 원<br>4~6: +40만 원</strong><small>성공 확률 50%</small></button></div>`;
  if(state.phase===PHASES.FATE_ROLLING)return '<div class="action-copy"><h3>도전 주사위 확인</h3><p>결과는 이미 저장됐습니다. 확인 중 다시 굴려지지 않습니다.</p><button type="button" class="primary-button" data-action="resume-fate-roll">주사위 결과 확인 🎲</button></div>';
  if(state.phase===PHASES.TROJAN_DECISION||state.phase===PHASES.GHOST_CITY_DECISION){const ghost=state.phase===PHASES.GHOST_CITY_DECISION;const targets=ghost?getGhostCityTargets(state):getTrojanTargets(state);return `<div class="temporary-city-decision"><span class="action-kicker">${ghost?'GHOST CITY':'TROJAN HORSE'}</span><h3>${ghost?'유령도시로 만들 내 도시':'목마를 설치할 상대 도시'}</h3><p>${ghost?'1라운드 동안 호텔 2개 단계입니다. 원래 건물은 보존되며 임시 건물은 매각할 수 없습니다.':'2라운드 안에 소유주가 받을 다음 통행료 수익 한 번을 가로챕니다. 우대권으로 전액 면제되면 목마는 남습니다.'}</p><div class="temporary-city-list">${targets.map(item=>`<button type="button" data-action="${ghost?'choose-ghost-city':'choose-trojan-city'}" data-tile="${item.id}"><i>${ghost?'👻':'🎁'}</i><span><b>${escapeHtml(item.name)}</b><small>${ghost?`${escapeHtml(buildingLabel(item))} → 호텔 2개`:escapeHtml(state.players.find(p=>p.id===item.ownerId).name)}</small></span><strong>선택</strong></button>`).join('')}</div></div>`}
  if(state.phase===PHASES.BERMUDA_DECISION)return `<div class="bermuda-decision"><span class="action-kicker">BERMUDA TRIANGLE</span><h3>누구와 위치를 바꿀까요?</h3><p>무인도에 있는 플레이어는 제외됩니다. 위치만 바꾸며 월급·통행료·도착 효과는 없습니다.</p><div class="bermuda-target-list">${getBermudaTargets(state).map(other=>`<button type="button" data-action="choose-bermuda-player" data-player="${other.id}" style="--target-color:${other.color}"><i>✈</i><span><b>${escapeHtml(other.name)}</b><small>${escapeHtml(state.board[other.position].name)}</small></span><strong>교환 ⇄</strong></button>`).join('')}</div></div>`;
  if(state.phase===PHASES.END_TURN&&state.eventQueue?.length)return `<div class="action-copy"><span class="action-kicker">GOLDEN KEY ×2</span><h3>다음 카드도 적용합니다</h3><p>앞 카드 처리가 끝났습니다. 남은 ${state.eventQueue.length}장을 순서대로 확인하세요.</p></div><button class="primary-button" type="button" data-action="resolve-next-event">다음 황금열쇠 확인 <span>◆</span></button>`;
  if(state.phase===PHASES.END_TURN&&state.auctionAfterEvents)return '<button class="primary-button" type="button" data-action="end-turn">황금열쇠 처리 완료 · 경매 시작</button>';
  if(state.phase===PHASES.WAITING_FOR_ROLL){
    if(player.skipTurns>0&&state.board[player.position]?.id==='deserted-island'){const hasEscape=player.specialCards.includes('island-escape');return `<div class="action-copy island-turn"><span class="action-kicker warning">DESERTED ISLAND</span><h3>더블이면 즉시 탈출!</h3><p>더블이나 탈출권으로 먼저 나갈 수 있고, 세 번째 차례에는 자동으로 탈출합니다.</p></div><div class="dice-row">${die(state.dice[0])}${die(state.dice[1])}<b>${state.rollTotal||'?'}</b></div><button class="roll-button" type="button" data-action="roll-dice">탈출 주사위 굴리기 <span>🎲</span></button>${hasEscape?'<button class="secondary-button wide card-use-button" type="button" data-action="use-special-card" data-card="island-escape">무인도 탈출권 사용</button>':''}`}
    const buildable=state.gameStage==='SECOND_HALF'&&getBuildableOwnedCities(state).length>0;const remaining=getUnownedPurchasableAssets(state).length;return `<div class="action-copy"><span class="action-kicker">${state.gameStage==='FIRST_HALF'?'FIRST HALF':'SECOND HALF'}</span><h3>주사위를 굴리세요</h3><p>${state.gameStage==='FIRST_HALF'?`건설 없이 토지를 매입합니다. 미분양 ${remaining}개는 전원 동의 시 바로 경매할 수 있습니다.`:'주사위 전에 어느 보유 도시든 자유롭게 개발할 수 있습니다.'}</p></div><div class="dice-row">${die(state.dice[0])}${die(state.dice[1])}<b>${state.rollTotal||'?'}</b></div>${buildable?'<button class="build-anywhere-button" type="button" data-action="open-build-mode">내 도시 자유 건설 <span>▥</span></button>':''}<button class="roll-button" type="button" data-action="roll-dice">주사위 굴리기 <span>🎲</span></button>${state.gameStage==='FIRST_HALF'?`<button class="early-auction-button" type="button" data-action="propose-early-auction">남은 ${remaining}개 조기 경매 제안 <span>🔨</span></button>`:''}<button class="secondary-button wide" type="button" data-action="open-trade">거래하기</button>`;
  }
  if(state.phase===PHASES.ROLLING||state.phase===PHASES.MOVING||state.phase===PHASES.RESOLVING_TILE)return `<div class="rolling-state"><div class="dice-row rolling">${die(state.dice[0])}${die(state.dice[1])}</div><h3>${state.phase===PHASES.ROLLING?'주사위가 구르는 중…':'여행 중…'}</h3><p>도착지의 새로운 기회를 확인하고 있어요.</p></div>`;
  if(state.phase===PHASES.BUY_DECISION)return `<div class="asset-decision" style="--region:${regionMeta(tile.region).color}"><span class="decision-icon">${tile.icon}</span><p>${tile.type==='city'?regionMeta(tile.region).name:'특별 시설'}</p><h3>${escapeHtml(tile.name)}</h3><dl><div><dt>인수 가격</dt><dd>${formatMoney(tile.purchasePrice)}</dd></div><div><dt>기본 통행료</dt><dd>${formatMoney(tile.baseRent)}</dd></div></dl><button class="primary-button" type="button" data-action="buy-tile" ${player.money<tile.purchasePrice?'disabled':''}>인수하기 <span>−${formatMoney(tile.purchasePrice)}</span></button><button class="secondary-button wide" type="button" data-action="decline-decision">이번에는 지나가기</button></div>`;
  if(state.phase===PHASES.BUILD_DECISION){
    const maxLevel=maxBuildingLevel(tile);const maxed=tile.buildingLevel>=maxLevel;const cost=maxed?0:tile.buildingCosts[tile.buildingLevel];
    return `<div class="asset-decision build" style="--region:${regionMeta(tile.region).color}"><span class="decision-icon">${maxed?'★':escapeHtml(tile.landmarkGlyph||'▥')}</span><p>${regionMeta(tile.region).name} · ${escapeHtml(buildingLabel(tile))}${tile.industrialized?' · 🏭 산업화':''}</p><h3>${escapeHtml(tile.name)} 개발</h3>${maxed?`<div class="landmark-complete">${escapeHtml(tile.landmarkName)} ${maxLevel-2}동 완성</div>`:`<dl><div><dt>건설 비용</dt><dd>${formatMoney(cost)}</dd></div><div><dt>다음 통행료</dt><dd>${formatMoney(tile.rentByLevel[tile.buildingLevel+1])}</dd></div></dl><button class="primary-button" type="button" data-action="build-tile" ${player.money<cost?'disabled':''}>${escapeHtml(buildingLabel(tile,tile.buildingLevel+1))} <span>−${formatMoney(cost)}</span></button>`}<button class="secondary-button wide" type="button" data-action="decline-decision">건설하지 않기</button></div>`;
  }
  if(state.phase===PHASES.BUILD_ANYWHERE_DECISION){const cities=getBuildableOwnedCities(state);return `<div class="build-anywhere-decision"><span class="action-kicker">FREE DEVELOPMENT</span><h3>어느 도시를 개발할까요?</h3><p>후반전에는 땅을 직접 밟지 않아도 주사위를 굴리기 전에 보유 도시를 원하는 만큼 개발할 수 있습니다.</p><div class="build-city-list">${cities.length?cities.map(item=>{const cost=item.buildingCosts[item.buildingLevel];return `<button type="button" data-action="build-owned-city" data-tile="${item.id}" ${player.money<cost?'disabled':''}><i>${escapeHtml(item.landmarkGlyph||'▥')}</i><span><b>${escapeHtml(item.name)}</b><small>${escapeHtml(buildingLabel(item,item.buildingLevel+1))}</small></span><strong>−${formatMoney(cost)}</strong></button>`}).join(''):'<p class="empty-copy">더 개발할 수 있는 도시가 없습니다.</p>'}</div><button class="secondary-button wide" type="button" data-action="finish-build-mode">건설 완료</button></div>`}
  if(state.phase===PHASES.EARLY_AUCTION_VOTE){const vote=state.earlyAuctionVote;return `<div class="early-auction-vote"><span class="action-kicker warning">UNANIMOUS VOTE</span><h3>남은 ${vote.remainingTileCount}개를 경매할까요?</h3><p><b>${escapeHtml(player.name)}</b>의 선택입니다. 한 명이라도 반대하면 전반전을 계속합니다.</p><div class="vote-progress">${vote.voterIds.map(id=>{const voter=state.players.find(item=>item.id===id);const done=vote.approvedIds.includes(id);return `<span class="${done?'approved':id===vote.currentVoterId?'current':''}" title="${escapeHtml(voter.name)}">${done?'✓':voter.token}</span>`}).join('')}</div><button class="primary-button" type="button" data-action="cast-early-auction-vote" data-approved="true">경매에 동의 <span>✓</span></button><button class="secondary-button wide" type="button" data-action="cast-early-auction-vote" data-approved="false">반대 · 전반전 계속</button></div>`}
  if(state.phase===PHASES.AUCTION){const auction=state.auction;const bidder=getAuctionBidder(state);const highest=state.players.find(item=>item.id===auction.highestBidderId);const required=auction.currentBid?auction.currentBid+RULES.AUCTION_MIN_INCREMENT:auction.minimumBid;const total=auction.completed+1+auction.queue.length;return `<div class="auction-decision" style="--region:${regionMeta(tile.region).color}"><span class="action-kicker warning">HALFTIME AUCTION · ${auction.completed+1}/${total}</span><span class="decision-icon">${tile.icon}</span><h3>${escapeHtml(tile.name)}</h3><p>${escapeHtml(bidder.name)}의 입찰 차례입니다.</p><dl><div><dt>현재 최고가</dt><dd>${auction.currentBid?formatMoney(auction.currentBid):'아직 없음'}</dd></div><div><dt>최고 입찰자</dt><dd>${highest?escapeHtml(highest.name):'—'}</dd></div><div><dt>최소 입찰가</dt><dd>${formatMoney(required)}</dd></div></dl><form data-auction-bid-form><input name="auctionBid" type="number" min="${required}" max="${bidder.money}" step="${RULES.AUCTION_MIN_INCREMENT}" value="${required}" aria-label="입찰 금액"><button class="primary-button" type="submit" ${bidder.money<required?'disabled':''}>${escapeHtml(bidder.name)} 입찰 <span>→</span></button></form><button class="secondary-button wide" type="button" data-action="pass-auction">이번 자산 패스</button><small class="auction-note">모두 패스하면 마지막 참여자가 최저가에 자동 낙찰받습니다.</small></div>`}
  if(state.phase===PHASES.TRAVEL_DECISION){
    return `<div class="travel-decision"><span class="action-kicker">SPACE TRAVEL</span><h3>게임판에서 도시를 누르세요</h3><p>노란빛으로 표시된 도시를 직접 누르면 즉시 이동하고 도착 효과를 적용합니다.</p><div class="travel-board-hint"><i>✦</i><span>목적지 도시 선택 대기 중</span></div></div>`;
  }
  if(state.phase===PHASES.WORLD_CUP_DECISION){const cities=state.board.filter(item=>item.type==='city'&&item.ownerId===player.id);return `<div class="world-cup-decision"><span class="action-kicker">WORLD CUP · IMMEDIATE</span><h3>즉시 개최할 도시를 선택하세요</h3><p>카드는 보관되지 않습니다. 선택한 도시의 통행료가 다음 자신의 3번 차례 동안 2배가 됩니다.</p><div class="world-cup-city-list">${cities.map(item=>`<button type="button" data-action="choose-world-cup-city" data-tile="${item.id}"><i>${escapeHtml(item.landmarkGlyph||'▥')}</i><span><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.landmarkName||'대표 랜드마크')}</small></span><strong>선택</strong></button>`).join('')}</div></div>`}
  if(state.phase===PHASES.TERROR_TARGET_DECISION){const targets=state.board.filter(item=>item.type==='city'&&effectiveBuildingLevel(item)>0);const remaining=state.pendingAction.remainingTargets;return `<div class="terror-decision"><span class="action-kicker warning">911 · IMMEDIATE</span><h3>파괴할 도시를 ${remaining}곳 더 지정하세요</h3><p>서로 다른 도시를 최대 두 곳 선택합니다. 판에서 붉게 표시된 도시나 아래 목록을 누르면 그곳의 건물이 모두 파괴됩니다.</p><div class="terror-target-list">${targets.map(item=>`<button type="button" data-action="choose-terror-target" data-tile="${item.id}"><i>✈</i><span><b>${escapeHtml(item.name)}</b><small>${escapeHtml(buildingLabel(item))}${item.industrialized?' · 산업화 유지':''}</small></span><strong>폭격</strong></button>`).join('')}</div></div>`}
  if(state.phase===PHASES.INDUSTRIALIZATION_DECISION){const targets=state.board.filter(item=>item.type==='city'&&item.ownerId===player.id&&item.buildable!==false&&!hasGhostCity(item)&&item.buildingLevel<RULES.INDUSTRIALIZED_MAX_BUILDING_LEVEL);return `<div class="industrialization-decision"><span class="action-kicker">INDUSTRIALIZATION · IMMEDIATE</span><h3>산업화할 도시를 선택하세요</h3><p>은행이 완성 건물 1동을 무료로 세웁니다. 선택한 도시는 폭격 후에도 산업화가 유지되며 최대 3동까지 개발할 수 있습니다.</p><div class="industrialization-city-list">${targets.map(item=>`<button type="button" data-action="choose-industrialization-city" data-tile="${item.id}"><i>🏭</i><span><b>${escapeHtml(item.name)}</b><small>${escapeHtml(buildingLabel(item))}${item.industrialized?' · 이미 산업화':''}</small></span><strong>선택</strong></button>`).join('')}</div><small class="industrialization-note">통행료는 전액 지불되지만 소유주는 80%만 받고 20%는 은행에 반환합니다.</small></div>`}
  if(state.phase===PHASES.PAYMENT_DECISION){const debt=state.pendingDebt;return `<div class="debt-panel payment-choice"><span class="action-kicker warning">TOLL PAYMENT</span><h3>${escapeHtml(debt.reason)}</h3><p class="debt-total">${formatMoney(debt.amount)} <small>우대권을 사용할지 직접 선택하세요.</small></p><button class="primary-button" type="button" data-action="use-special-card" data-card="toll-waiver">우대권 사용 <span>◇</span></button><button class="secondary-button wide" type="button" data-action="settle-debt">${player.money>=debt.amount?'현금으로 지불':'우대권 없이 자산 정리'}</button></div>`}
  if(state.phase===PHASES.ASSET_MANAGEMENT)return debtPanel(state);
  if(state.phase===PHASES.END_TURN)return `<div class="action-copy end-turn"><span class="action-kicker">TURN COMPLETE</span><h3>턴을 마칩니다</h3><p>${state.rolledDouble?'더블이면 한 번 더 여행할 수 있어요.':'다음 차례로 바로 이어집니다.'}</p></div><div class="dice-row">${die(state.dice[0])}${die(state.dice[1])}<b>${state.rollTotal||'—'}</b></div><button class="primary-button" type="button" data-action="end-turn">턴 종료 <span>→</span></button>`;
  return `<div class="rolling-state"><h3>${phaseLabel[state.phase]}</h3></div>`;
}

function debtPanel(state){
  const player=getPaymentPlayer(state);const debt=state.pendingDebt;const assets=state.board.filter(tile=>tile.ownerId===player.id);const cards=player.specialCards||[];
  const assetRows=assets.map(tile=>`<article><span><b>${escapeHtml(tile.name)}</b><small>${tile.type==='city'?`${escapeHtml(buildingLabel(tile,tile.buildingLevel))}${tile.industrialized?' · 🏭 산업화':''}${hasGhostCity(tile)?' · 매각 시 유령도시 해제':''}`:'탈것'}</small></span><span>${tile.buildingLevel>0?`<button type="button" data-action="sell-building" data-tile="${tile.id}">건물 +${formatMoney(tile.buildingCosts[tile.buildingLevel-1]*RULES.SELL_BUILDING_RATE)}</button>`:`<button type="button" data-action="sell-asset" data-tile="${tile.id}">제값 매각 +${formatMoney(tile.purchasePrice*RULES.SELL_PROPERTY_RATE)}</button>`}</span></article>`);
  const cardRows=cards.map(cardId=>{const card=SPECIAL_CARD_INFO[cardId];return `<article><span><b>${card.icon} ${escapeHtml(card.name)}</b><small>보관 중인 황금열쇠</small></span><span><button type="button" data-action="sell-special-card" data-card="${cardId}">매각 +${formatMoney(card.sellPrice)}</button></span></article>`});
  return `<div class="debt-panel"><span class="action-kicker warning">PAYMENT DUE</span><h3>${escapeHtml(debt.reason)}</h3><p class="debt-total">필요 ${formatMoney(debt.amount)} <small>현재 ${formatMoney(player.money)}</small></p><div class="liquidation-list">${assetRows.length||cardRows.length?[...assetRows,...cardRows].join(''):'<p class="empty-copy">매각할 자산이 없습니다.</p>'}</div><button class="primary-button" type="button" data-action="settle-debt" ${player.money<debt.amount?'disabled':''}>${formatMoney(debt.amount)} 지불 <span>→</span></button><button class="danger-button" type="button" data-action="declare-bankruptcy">파산 선언</button></div>`;
}

function currentAssets(state){
  const player=getPaymentPlayer(state);const assets=state.board.filter(tile=>tile.ownerId===player.id);const cards=player.specialCards||[];
  const canSellCard=[PHASES.WAITING_FOR_ROLL,PHASES.END_TURN,PHASES.ASSET_MANAGEMENT].includes(state.phase);
  const assetsMarkup=assets.map(tile=>`<span style="--asset:${regionMeta(tile.region).color}"><i>${tile.type==='city'&&tile.buildingLevel>0?escapeHtml(tile.landmarkGlyph||tile.icon):tile.icon}</i>${escapeHtml(tile.name)}${tile.type==='city'?` · ${escapeHtml(buildingLabel(tile))}${tile.industrialized?' · 🏭 산업화':''}${tile.worldCupTurns>0?` · ⚽ ×2 (${tile.worldCupTurns}턴)`:''}`:''}</span>`).join('');
  const cardsMarkup=cards.map(cardId=>{const card=SPECIAL_CARD_INFO[cardId];return `<span class="special-card-chip" style="--asset:#ffd95c"><i>${card.icon}</i>${escapeHtml(card.name)}<button type="button" data-action="sell-special-card" data-card="${cardId}" title="${formatMoney(card.sellPrice)}에 매각" ${canSellCard?'':'disabled'}>매각</button></span>`}).join('');
  return `${player.gamblerPending?'<aside class="gambler-pending"><b>🎲 라스베가스의 도박사</b><span>내 다음 주사위에 자동 적용</span><small>2~6 손실 · 7 변동 없음 · 8~12 획득</small></aside>':''}<section class="asset-summary"><div class="section-label"><span>MY PORTFOLIO</span><b>${assets.length+cards.length}</b></div><div class="asset-chips">${assetsMarkup||cardsMarkup?assetsMarkup+cardsMarkup:'<p>아직 보유한 자산이 없습니다.</p>'}</div></section>`;
}

function activity(state){return `<section class="activity-log"><div class="section-label"><span>TRAVEL LOG</span></div>${state.log.slice(0,4).map(entry=>`<p>${escapeHtml(entry.message)}</p>`).join('')}</section>`}

function noticeModal(state){
  if(!state.notice)return '';
  const golden=state.notice.source==='golden-key';
  return `<div class="modal-backdrop${golden?' golden-key-backdrop':''}" role="dialog" aria-modal="true" aria-labelledby="notice-title"><section class="notice-card tone-${state.notice.tone}${golden?' golden-key-draw-card':''}"><span class="notice-symbol">${golden?'◆':state.notice.tone==='landmark'?'★':state.notice.tone==='danger'?'!':'✦'}</span><p class="eyebrow">${golden?'GOLDEN KEY':'TRAVEL UPDATE'}</p><h2 id="notice-title">${escapeHtml(state.notice.title)}</h2><p>${escapeHtml(state.notice.message)}</p><button class="primary-button" type="button" data-action="dismiss-notice">확인 <span>→</span></button></section></div>`;
}

function optionAssets(assets){return `<option value="">자산 없음</option>${assets.map(tile=>`<option value="${tile.id}">${escapeHtml(tile.name)}</option>`).join('')}`}
function tradeModal(state){
  if(state.phase!==PHASES.TRADE)return '';
  const proposer=getCurrentPlayer(state);const others=state.players.filter(player=>player.id!==proposer.id&&!player.bankrupt);const trade=state.trade;
  if(trade.stage==='review'){
    const partner=state.players.find(player=>player.id===trade.partnerId);const offered=state.board.find(tile=>tile.id===trade.offerAssetId);const requested=state.board.find(tile=>tile.id===trade.requestAssetId);
    return `<div class="modal-backdrop" role="dialog" aria-modal="true"><section class="trade-card"><p class="eyebrow">TRADE REVIEW</p><h2>${escapeHtml(partner.name)}</h2><p class="trade-intro">${escapeHtml(proposer.name)}의 거래 제안입니다.</p><div class="trade-review"><article><span>받는 것</span><b>${trade.offerCash?`${formatMoney(trade.offerCash)} 현금`:''}${trade.offerCash&&offered?' + ':''}${offered?escapeHtml(offered.name):''}</b></article><i>⇄</i><article><span>주는 것</span><b>${trade.requestCash?`${formatMoney(trade.requestCash)} 현금`:''}${trade.requestCash&&requested?' + ':''}${requested?escapeHtml(requested.name):''}</b></article></div><button class="primary-button" type="button" data-action="accept-trade">거래 수락 <span>✓</span></button><button class="secondary-button wide" type="button" data-action="reject-trade">거래 거절</button></section></div>`;
  }
  const otherAssets=others.flatMap(player=>getTradeableAssets(state,player.id).map(tile=>({...tile,ownerName:player.name})));
  return `<div class="modal-backdrop" role="dialog" aria-modal="true"><form class="trade-card" data-trade-form><p class="eyebrow">PLAYER TRADE</p><h2>자산 거래 제안</h2><label>거래 상대<select name="partnerId">${others.map(player=>`<option value="${player.id}">${escapeHtml(player.name)}</option>`).join('')}</select></label><div class="trade-columns"><fieldset><legend>내가 주는 것</legend><label>현금<input type="number" name="offerCash" min="0" max="${proposer.money}" step="10000" value="0"></label><label>자산<select name="offerAssetId">${optionAssets(getTradeableAssets(state,proposer.id))}</select></label></fieldset><fieldset><legend>내가 받는 것</legend><label>현금<input type="number" name="requestCash" min="0" step="10000" value="0"></label><label>자산<select name="requestAssetId"><option value="">자산 없음</option>${otherAssets.map(tile=>`<option value="${tile.id}">${escapeHtml(tile.ownerName)} · ${escapeHtml(tile.name)}</option>`).join('')}</select></label></fieldset></div><p class="trade-note">건물이 있는 도시는 먼저 건물을 정리해야 거래할 수 있습니다.</p><button class="primary-button" type="submit">제안하기 <span>→</span></button><button class="secondary-button wide" type="button" data-action="cancel-trade">취소</button></form></div>`;
}

function gameOverModal(state){
  if(state.status!=='finished')return '';
  const ranking=[...state.players].sort((a,b)=>getNetWorth(state,b.id)-getNetWorth(state,a.id));
  return `<div class="modal-backdrop" role="dialog" aria-modal="true"><section class="gameover-card"><span class="winner-crown">♛</span><p class="eyebrow">JOURNEY COMPLETE</p><h2>${state.winnerIds.length>1?'공동 우승!':`${escapeHtml(state.players.find(player=>player.id===state.winnerIds[0])?.name)} 승리!`}</h2><p>${state.finishedReason==='time-limit'?'제한 시간이 끝나 순자산을 비교했습니다.':'마지막까지 살아남은 타이쿤입니다.'}</p><div class="ranking">${ranking.map((player,index)=>`<article><b>${index+1}</b><i style="--player-color:${player.color}">${player.token}</i><span>${escapeHtml(player.name)}</span><strong>${formatMoney(getNetWorth(state,player.id))}</strong></article>`).join('')}</div><button class="primary-button" type="button" data-action="new-game-from-finish">새 게임 <span>→</span></button></section></div>`;
}

export function renderGame(root,state){
  const existingGame=root.querySelector('.in-game');const viewport=existingGame&&globalThis.window?{left:globalThis.window.scrollX||0,top:globalThis.window.scrollY||0}:null;
  const previousGauge=root.querySelector('[data-loan-remaining]');const previousLoanPlayer=previousGauge?.dataset.loanPlayer;const previousLoanRemaining=Number(previousGauge?.dataset.loanRemaining);
  const player=state.phase===PHASES.AUCTION?getAuctionBidder(state):state.phase===PHASES.EARLY_AUCTION_VOTE?getEarlyAuctionVoter(state):getPaymentPlayer(state);
  root.innerHTML=`<main class="in-game"><header class="game-topbar"><div class="game-brand"><span>WT</span><b>WORLD TYCOON</b></div><div class="game-meta"><span>SAVE ${state.saveSlot||1}</span><b data-timer>${timerLabel(state)}</b><span>TURN ${state.turnNumber}</span></div><div class="utility-actions"><button type="button" data-action="open-help" aria-label="게임 방법">?</button><button type="button" data-action="open-menu" aria-label="게임 메뉴">☰</button></div></header>${playerStrip(state)}<div class="stage-banner stage-${String(state.gameStage).toLowerCase()}"><b>${stageLabel[state.gameStage]||'게임 진행'}</b><span>${state.gameStage==='FIRST_HALF'?`미분양 ${getUnownedPurchasableAssets(state).length}개 · 전원 동의 시 조기 경매`:state.gameStage==='AUCTION'?`경매 ${state.auction.completed+1}번째`:'자유 건설 가능'}</span></div><div class="play-layout"><section class="board-panel">${boardMarkup(state)}</section><aside class="control-panel turn-panel" style="--player-color:${player.color}"><div class="current-player"><span class="current-token">${player.token}</span><div><small>${state.phase===PHASES.AUCTION?'CURRENT BIDDER':state.phase===PHASES.EARLY_AUCTION_VOTE?'CURRENT VOTER':'CURRENT PLAYER'}</small><h2>${escapeHtml(player.name)}</h2></div><strong>${formatMoney(player.money)}<small>보유 현금</small></strong></div><div class="phase-pill">${phaseLabel[state.phase]}</div>${globalEffectsPanel(state)}<section class="turn-actions">${decisionPanel(state)}</section>${bankPanel(state)}${currentAssets(state)}${activity(state)}</aside></div></main><div id="modal-root">${noticeModal(state)||tradeModal(state)||gameOverModal(state)}</div>`;
  const nextGauge=root.querySelector('[data-loan-remaining]');if(nextGauge){const samePlayer=nextGauge.dataset.loanPlayer===previousLoanPlayer;const remaining=Number(nextGauge.dataset.loanRemaining);nextGauge.classList.add(!previousGauge?'loan-created':samePlayer&&remaining<previousLoanRemaining?'loan-ticked':'loan-steady')}
  if(state.notice?.source==='golden-key')animateGoldenKeyDraw(root);
  if(viewport&&globalThis.window?.scrollTo){const restore=()=>globalThis.window.scrollTo(viewport.left,viewport.top);restore();globalThis.requestAnimationFrame?.(restore)}
}

export function renderHelp(){
  return `<div class="modal-backdrop free-modal" role="dialog" aria-modal="true"><section class="help-card"><button class="modal-close" type="button" data-action="close-free-modal" aria-label="닫기">×</button><p class="eyebrow">HOW TO PLAY</p><h2>World Tycoon 가이드</h2><div class="help-grid">${[
    ['🎲','주사위','주사위 2개의 합만큼 이동합니다. 무인도에서는 더블로 먼저 탈출할 수 있고, 세 번째 차례에는 자동으로 나옵니다.'],
    ['💾','저장 슬롯','서로 다른 게임 2개가 이 기기에 각각 자동 저장됩니다. 시작 화면에서 이어할 게임을 선택합니다.'],['◈','전반전','건설 없이 토지만 매입하며 상대 땅에서는 대지 통행료만 냅니다. 미분양 자산이 5개가 되거나 전원이 조기 경매에 동의하면 전반전이 끝납니다.'],
    ['🔨','하프타임 경매','전반전 종료 시 남은 모든 자산을 차례대로 공개 경매합니다. 최고 입찰자가 낙찰받고 모든 경매가 끝나면 후반전이 시작됩니다.'],['▥','후반전 건설','주사위를 굴리기 전에는 땅을 직접 밟지 않아도 어느 보유 도시든 원하는 만큼 개발할 수 있습니다.'],
    ['₩','통행료','상대 도시나 탈것에 도착하면 표시된 통행료를 냅니다. 우대권은 지불 직전에 직접 선택해 사용합니다.'],['◆','황금열쇠','우대권과 무인도 탈출권은 필요한 순간에 직접 사용하거나 은행에 팔 수 있습니다.'],
    ['↻','황금 열쇠 리셋',`남은 장수와 관계없이 전체 ${EVENT_CARDS.length}장을 다시 채우고 무작위로 섞습니다. 리셋 카드도 포함하며, 보유 카드·발동 중인 효과·이미 뽑은 추가 카드는 유지됩니다.`],
    ['🎲','운명의 갈림길','즉시 안전한 15만 원 수입 또는 주사위 한 개 도전을 선택합니다. 1~3은 20만 원 손실, 4~6은 40만 원 획득입니다. 도원결의는 적용되지만 이동·더블·라스베가스의 도박사에는 영향을 주지 않습니다.'],
    ['🎁','트로이 목마','상대 도시 하나의 다음 통행료 수익을 한 번 가로챕니다. 2라운드 동안 유효하며 전액 면제되면 남습니다. 산업화 은행 몫은 유지하고 수입에는 도원결의를 적용합니다. 일제의 수탈로 소유주가 수익을 받지 못하면 발동을 기다립니다. 소유권 변경 또는 설치자 파산 시 해제됩니다.'],
    ['👻','유령도시','건설 가능한 내 도시를 1라운드 동안 호텔 2개(랜드마크 2동)로 만듭니다. 전반전에도 해당 통행료를 받습니다. 임시 호텔은 순자산·매각가·유지비에 포함되지 않습니다. 추가 건설·산업화는 기간이 끝난 뒤 가능하며, 파괴되면 원래 건물도 함께 사라집니다. 매각·거래 시 효과가 해제됩니다. 기간은 생존 인원만큼의 일반 차례로, 발동 차례와 더블 추가 차례는 제외합니다.'],
    ['⇄','버뮤다 삼각지대','다른 생존 플레이어를 직접 선택해 위치만 교환합니다. 무인도에 있는 사람은 제외되며, 월급·통행료·도착 효과는 발생하지 않습니다. 미국의 분노 중에는 무효입니다.'],
    ['🤝','도원결의','무작위 상대와 2라운드(발동 시 생존 인원×2회의 일반 차례, 더블 제외) 동안 수입·벌금·사회복지기금·통행료를 반씩 나눕니다. 서로의 통행료는 방문자만 절반을 지불합니다. 산업화는 은행 몫을 뺀 수익을 나눕니다. 구입·건설·매각·대출·거래는 제외됩니다. 새 결의는 두 사람의 이전 결의를 대체하고 한쪽이 파산하면 해제됩니다.'],
    ['×2','묻고 더블로 가!','다음에 누구든 황금열쇠를 처음 뽑으면 두 장을 확보하고, 각 카드의 선택과 정산까지 순서대로 적용합니다. 턴 제한 없이 대기합니다. 이미 확보한 두 번째 카드는 새로운 뽑기가 아닙니다. 효과는 4장으로 중첩되지 않습니다.'],
    ['🎲','라스베가스의 도박사','다음 내 주사위로 한 번 정산합니다. 2~6은 합×10만 원 손실, 7은 변동 없음, 8~12는 (합−6)×10만 원 획득입니다. 12는 60만 원입니다. 더블 보너스와 무인도 탈출 주사위도 포함하며, 돈이 부족하면 정리 후 같은 주사위로 이동합니다.'],
    ['✈','탈것','콩코드·퀸 엘리자베스호 여행과 콜럼비아호를 이용하는 우주여행은 소유자에게 이용료를 냅니다. 목적지는 판의 도시를 직접 눌러 선택합니다.'],['⚽','월드컵','카드를 뽑는 즉시 보유 도시 하나를 골라 다음 자신의 3번 차례 동안 통행료를 2배로 올립니다.'],
    ['🇯🇵','일제의 수탈','즉시 3라운드 동안 제주도·부산·서울 통행료가 도쿄 소유주에게 귀속됩니다. 도쿄가 미소유면 은행이 회수합니다.'],['⛔','911 테러','즉시 서로 다른 도시를 최대 두 곳 지정해 건물을 전부 파괴합니다. 이어지는 2라운드에는 이동수단과 특수 이동이 봉쇄됩니다.'],['🏭','산업화','즉시 내 도시 하나에 완성 건물 1동을 무료로 세웁니다. 해당 도시는 영구적으로 3동까지 개발되며 통행료 수익의 20%를 은행에 반환합니다.'],['⚖','제네바 협정','즉시 2라운드 동안 무인도 출입과 갇힘 효과를 막고, 이미 갇힌 플레이어도 풀어줍니다.'],
    ['⇄','거래','주사위를 굴리기 전에 현금·도시·탈것을 다른 플레이어와 교환할 수 있습니다. 건물 있는 도시는 거래할 수 없습니다.'],
    ['🏦','은행 대출','자기 차례에 원금 합계 최대 100만 원까지 빌릴 수 있습니다. 고정 이자 10%이며 대출 뒤 3바퀴 안에 전액 상환하지 못하면 파산합니다.'],['!','파산','현금이 부족하면 땅은 매입가 전액에, 건물은 반값에 정리합니다. 모두 정리해도 못 내거나 대출 만기를 지키지 못하면 파산합니다.'],['♛','승리','완전 게임은 마지막 생존자가, 시간제 게임은 종료 시 대출을 뺀 순자산 1위가 승리합니다.']
  ].map(([icon,title,copy])=>`<article><i>${icon}</i><span><b>${title}</b><p>${copy}</p></span></article>`).join('')}</div></section></div>`;
}

export function renderMenu(){return `<div class="modal-backdrop free-modal" role="dialog" aria-modal="true"><section class="menu-card"><p class="eyebrow">GAME MENU</p><h2>여행을 멈출까요?</h2><p>진행 상황은 이 기기에 자동 저장됩니다.</p><button class="primary-button" type="button" data-action="close-free-modal">게임 계속 <span>→</span></button><button class="secondary-button wide" type="button" data-action="choose-save-slot">다른 저장 슬롯 선택</button><button class="danger-button" type="button" data-action="confirm-new-game">현재 저장 삭제 후 새 게임</button></section></div>`}

export function showFreeModal(markup){document.querySelector('#modal-root')?.replaceChildren(document.createRange().createContextualFragment(markup))}
export function closeFreeModal(){document.querySelector('#modal-root')?.replaceChildren()}
export function toast(message){const element=document.createElement('div');element.className='toast';element.textContent=message;document.body.append(element);requestAnimationFrame(()=>element.classList.add('show'));setTimeout(()=>{element.classList.remove('show');setTimeout(()=>element.remove(),200)},2300)}
export function updateTimer(state){const timer=document.querySelector('[data-timer]');if(timer)timer.textContent=timerLabel(state)}

export function showDiceResult(dice,total){
  document.querySelector('.dice-result-feedback')?.remove();const element=document.createElement('div');element.className='dice-result-feedback';element.setAttribute('role','status');element.setAttribute('aria-live','assertive');
  element.innerHTML=`<small>DICE RESULT</small><div>${die(dice[0])}${die(dice[1])}</div><strong>${total}칸 이동</strong><span>${dice[0]} + ${dice[1]} = ${total}</span>${dice[0]===dice[1]?'<b class="dice-double-badge">더블!</b>':''}`;document.body.append(element);requestAnimationFrame(()=>element.classList.add('show'));
  return new Promise(resolve=>setTimeout(()=>{element.classList.remove('show');setTimeout(()=>{element.remove();resolve()},240)},1050));
}

function cinematicDiceFace(value,className){
  const dots={1:[5],2:[1,9],3:[1,5,9],4:[1,3,7,9],5:[1,3,5,7,9],6:[1,3,4,6,7,9]}[value];return `<span class="cinematic-dice-face ${className}">${Array.from({length:9},(_,index)=>`<i class="${dots.includes(index+1)?'on':''}"></i>`).join('')}</span>`;
}
function cinematicDie(value,index){
  const opposite=7-value;const sides=[1,2,3,4,5,6].filter(side=>side!==value&&side!==opposite);const right=sides[0];const left=7-right;const top=sides.find(side=>side!==right&&side!==left);const bottom=7-top;
  return `<span class="cinematic-die cinematic-die-${index}" data-cinematic-die="${value}" aria-hidden="true"><span class="cinematic-die-cube">${cinematicDiceFace(value,'face-front')}${cinematicDiceFace(opposite,'face-back')}${cinematicDiceFace(right,'face-right')}${cinematicDiceFace(left,'face-left')}${cinematicDiceFace(top,'face-top')}${cinematicDiceFace(bottom,'face-bottom')}</span></span>`;
}

export async function animateFateDie(face){
  const layer=document.createElement('div');const reduced=reducedMotion();const amount=face<=3?'−20만 원':'+40만 원';const animations=[];
  layer.className=reduced?'fate-roll-static':'dice-throw-animation fate-dice-animation show';layer.setAttribute('role','status');layer.setAttribute('aria-label',`운명의 갈림길 · 주사위 한 개 · ${face} · ${amount}`);
  layer.innerHTML=reduced?`<section><h2>운명의 갈림길</h2>${die(face)}<strong>${face} · ${amount}</strong><p>이동하지 않는 도전 주사위</p></section>`:`${cinematicDie(face,0)}<span class="dice-landing-total"><small>운명의 갈림길</small><b>${face}</b><em>${amount} · 이동 없음</em></span>`;
  document.body.append(layer);
  try{
    if(!reduced){const element=layer.querySelector('.cinematic-die');element.style.left='50%';element.style.top='46%';const cube=element.querySelector('.cinematic-die-cube');
      animations.push(element.animate([{transform:'translate(90px,-130px) scale(.7)'},{transform:'translate(-50%,-35%) scale(1)',offset:.7},{transform:'translate(-50%,-80%) scale(1)',offset:.83},{transform:'translate(-50%,-50%) scale(1)'}],{duration:1300,easing:'ease-out',fill:'both'}));
      animations.push(cube.animate([{transform:'rotateX(-390deg) rotateY(500deg) rotateZ(-110deg)'},{transform:'rotateX(40deg) rotateY(45deg) rotateZ(25deg)',offset:.7},{transform:'rotateX(-30deg) rotateY(25deg) rotateZ(-8deg)',offset:.83},{transform:'rotateX(-8deg) rotateY(10deg) rotateZ(-2deg)'}],{duration:1300,easing:'ease-out',fill:'both'}));
      await Promise.all(animations.map(animation=>animation.finished.catch(()=>{})));layer.classList.add('settled');
    }
    await pause(1100);
  }finally{animations.forEach(animation=>animation.cancel());layer.remove()}
}

export async function animateDiceThrow(dice,total){
  if(reducedMotion())return showDiceResult(dice,total);document.querySelector('.dice-throw-animation')?.remove();const center=document.querySelector('.board-center')?.getBoundingClientRect();const landingX=center?center.left+center.width*.52:globalThis.innerWidth*.48;const landingY=center?center.top+center.height*.55:globalThis.innerHeight*.53;const spacing=Math.min(118,Math.max(90,(center?.width||300)*.24));
  const layer=document.createElement('div');layer.className='dice-throw-animation';layer.setAttribute('role','status');layer.setAttribute('aria-label',`주사위 두 개가 오른쪽 위에서 가볍게 굴러 판 중앙에 떨어집니다. 결과는 ${dice[0]}과 ${dice[1]}, 합계 ${total}입니다.`);layer.innerHTML=`<span class="cinematic-dice-shadow shadow-one" style="left:${landingX-spacing/2}px;top:${landingY+31}px"></span><span class="cinematic-dice-shadow shadow-two" style="left:${landingX+spacing/2}px;top:${landingY+35}px"></span>${cinematicDie(dice[0],0)}${cinematicDie(dice[1],1)}<span class="dice-landing-total"><small>DICE RESULT</small><b>${total}</b><em>${dice[0]} + ${dice[1]} · ${total}칸</em></span>`;document.body.append(layer);
  if(dice[0]===dice[1]){const badge=document.createElement('span');badge.className='dice-double-badge';badge.textContent='더블!';layer.querySelector('.dice-landing-total').append(badge)}
  const elements=[...layer.querySelectorAll('.cinematic-die')];const animations=elements.flatMap((element,index)=>{const targetX=landingX+(index?spacing/2:-spacing/2);const targetY=landingY+(index?5:0);element.style.left=`${targetX}px`;element.style.top=`${targetY}px`;const startAnchorX=globalThis.innerWidth-70-(index?0:spacing*1.08);const startX=startAnchorX-targetX;const startY=54-targetY;const cube=element.querySelector('.cinematic-die-cube');const move=(x,y,z)=>`translate3d(calc(-50% + ${x}px),calc(-50% + ${y}px),${z}px)`;const rotate=(x,y,z)=>`rotateX(${x}deg) rotateY(${y}deg) rotateZ(${z}deg)`;const finalX=-8;const finalY=index?-10:10;const finalZ=index?2:-2;const delay=index*95;
    const flight=element.animate([{transform:move(startX,startY,118)},{transform:move(startX-12,startY+7,112),offset:.1},{transform:move(startX+7,startY-3,120),offset:.2},{transform:move(startX-9,startY+8,108),offset:.3},{transform:move(startX*.48,startY*.44,74),offset:.47},{transform:move(0,17,0),offset:.64},{transform:move(index?13:-12,-35,58),offset:.76},{transform:move(index?3:-3,7,0),offset:.9},{transform:move(0,0,0)}],{duration:1660,delay,easing:'cubic-bezier(.18,.64,.18,1)',fill:'forwards'}).finished.catch(()=>{});
    const spin=cube.animate([{transform:rotate(-386-index*24,506+index*31,-138)},{transform:rotate(-364-index*24,538+index*31,-116),offset:.1},{transform:rotate(-405-index*24,491+index*31,-151),offset:.2},{transform:rotate(-371-index*24,533+index*31,-120),offset:.3},{transform:rotate(-234,index?286:316,-78),offset:.47},{transform:rotate(finalX+57,finalY+46,finalZ+38),offset:.64},{transform:rotate(finalX-43,finalY+53,finalZ-19),offset:.76},{transform:rotate(finalX+11,finalY-9,finalZ+8),offset:.9},{transform:rotate(finalX,finalY,finalZ)}],{duration:1660,delay,easing:'cubic-bezier(.18,.64,.18,1)',fill:'forwards'}).finished.catch(()=>{});return [flight,spin]});requestAnimationFrame(()=>layer.classList.add('show'));await Promise.all(animations);layer.classList.add('settled');await pause(780);layer.remove();
}

export async function animateEarlyAuctionConsent(result){
  if(!result?.player)return;document.querySelector('.auction-consent-animation')?.remove();const approved=[...document.querySelectorAll('.vote-progress .approved')];approved[Math.max(0,result.approvedCount-1)]?.classList.add('stamp-approved');const layer=document.createElement('div');layer.className=`auction-consent-animation${result.final?' unanimous':''}`;layer.style.setProperty('--voter-color',result.player.color||'#5ce3c3');layer.setAttribute('role','status');layer.setAttribute('aria-label',`${result.player.name}이 조기 경매에 동의했습니다. ${result.approvedCount}명 중 ${result.total}명 동의.`);layer.innerHTML=`<div class="auction-consent-slip"><small>EARLY AUCTION CONSENT</small><span class="consent-player"><i>${escapeHtml(result.player.token||'✈')}</i><b>${escapeHtml(result.player.name)}</b></span><div class="consent-progress">${Array.from({length:result.total},(_,index)=>`<i class="${index<result.approvedCount?'approved':''}">${index<result.approvedCount?'✓':index+1}</i>`).join('')}</div><strong class="consent-stamp">동의<em>APPROVED</em></strong>${result.final?'<b class="unanimous-copy">전원 만장일치</b>':''}</div>`;document.body.append(layer);requestAnimationFrame(()=>layer.classList.add('show'));await pause(reducedMotion()?420:result.final?1150:820);layer.remove();
}

function animateGoldenKeyDraw(root){
  if(globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches)return;
  requestAnimationFrame(()=>{const deck=root.querySelector('.center-card-deck');const card=root.querySelector('.golden-key-draw-card');const backdrop=root.querySelector('.golden-key-backdrop');if(!deck||!card)return;
    const from=deck.getBoundingClientRect();const to=card.getBoundingClientRect();const dx=from.left+from.width/2-(to.left+to.width/2);const dy=from.top+from.height/2-(to.top+to.height/2);
    backdrop?.animate([{backgroundColor:'transparent',backdropFilter:'blur(0)'},{backgroundColor:'#020912d9',backdropFilter:'blur(9px)'}],{duration:560,easing:'ease-out'});
    card.animate([{opacity:.2,transform:`translate(${dx}px,${dy}px) scale(.16) rotate(-25deg)`},{opacity:1,transform:'translate(0,0) scale(1.04) rotate(1deg)',offset:.82},{opacity:1,transform:'translate(0,0) scale(1) rotate(0)'}],{duration:680,easing:'cubic-bezier(.2,.8,.2,1)'});
  });
}

export function captureTokenRect(playerId){
  const token=document.querySelector(`[data-player-token="${playerId}"]`);if(!token)return null;const rect=token.getBoundingClientRect();return {left:rect.left,top:rect.top,width:rect.width,height:rect.height};
}

export async function animateTokenStep(playerId,fromRect){
  const token=document.querySelector(`[data-player-token="${playerId}"]`);if(!token||!fromRect||globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches)return;
  const to=token.getBoundingClientRect();const dx=fromRect.left+fromRect.width/2-(to.left+to.width/2);const dy=fromRect.top+fromRect.height/2-(to.top+to.height/2);
  try{await token.animate([{transform:`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px)) scale(.92)`,filter:'brightness(1)'},{transform:'translate(-50%,-50%) scale(1.14)',filter:'brightness(1.35)',offset:.78},{transform:'translate(-50%,-50%) scale(1)',filter:'brightness(1)'}],{duration:270,easing:'cubic-bezier(.2,.75,.25,1)'}).finished}catch{}
}

export function animateBuildingDestruction(result){
  const tile=document.querySelector(`[data-tile-index="${Number(result?.tileIndex)}"]`);if(!tile)return Promise.resolve();
  const effect=document.createElement('span');effect.className='building-destruction-animation';effect.setAttribute('role','img');effect.setAttribute('aria-label',`${result.tileName}의 ${result.landmarkName} 건물이 비행기 충돌 연출 뒤 무너집니다.`);
  const glyph=escapeHtml(result.landmarkGlyph||'▥');const buildings=`<b>${glyph}</b>`.repeat(Math.max(1,Number(result.buildingCount)||1));effect.innerHTML=`<i class="destruction-plane">✈</i><span class="destruction-building">${buildings}</span><em class="destruction-impact">✦</em><small>건물 파괴</small>`;tile.append(effect);
  const reduced=globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches;return new Promise(resolve=>setTimeout(()=>{effect.remove();resolve()},reduced?650:1750));
}

export async function animateLandmarkConstruction(result,{industrial=false}={}){
  const tile=document.querySelector(`[data-tile-index="${Number(result?.tileIndex)}"]`);if(!tile)return;tile.querySelector('.landmark-construction-animation')?.remove();
  const level=Math.max(1,Number(result.newLevel)||1);const count=Math.max(1,level<3?1:level-2);const glyph=escapeHtml(result.landmarkGlyph||'▥');const stageNames=['땅','기초 배치','골조 조립','1동 완성','2동 완성','3동 완성'];
  const effect=document.createElement('span');effect.className=`landmark-construction-animation construction-stage-${level}${industrial?' industrial-construction':''}`;effect.setAttribute('role','status');effect.setAttribute('aria-label',`${result.tileName}에서 ${result.landmarkName||'대표 랜드마크'} ${stageNames[level]} 건설 연출이 진행됩니다.`);effect.innerHTML=`<span class="assembly-foundation"><i></i><i></i><i></i></span><span class="assembly-scaffold"><i></i><i></i><i></i><i></i></span><span class="assembly-site-crane"><i></i><b></b><em></em></span><span class="assembly-landmarks">${`<b>${glyph}</b>`.repeat(count)}</span><small>${escapeHtml(stageNames[level])}</small>`;
  tile.classList.add('construction-active');tile.append(effect);if(reducedMotion()){await pause(360)}else{requestAnimationFrame(()=>effect.classList.add('show'));await pause(industrial?1850:1450)}effect.remove();tile.classList.remove('construction-active');tile.classList.add('construction-complete-flash');await pause(reducedMotion()?120:430);tile.classList.remove('construction-complete-flash');
}

export async function animateIndustrialization(result){
  const tile=document.querySelector(`[data-tile-index="${Number(result?.tile?.index)}"]`);if(!tile)return;document.querySelector('.industrialization-animation')?.remove();const target=tile.getBoundingClientRect();const bank=document.querySelector('.bank-panel')?.getBoundingClientRect();const startX=bank?bank.left+bank.width/2:globalThis.innerWidth-48;const startY=bank?bank.top+bank.height/2:globalThis.innerHeight*.72;const targetX=target.left+target.width/2;const targetY=target.top+target.height/2;
  const layer=document.createElement('div');layer.className='industrialization-animation';layer.setAttribute('role','status');layer.setAttribute('aria-label',`은행 크레인이 ${result.tile.name}에 ${result.tile.landmarkName||'대표 랜드마크'}를 무료 건설합니다.`);layer.innerHTML=`<div class="industrialization-copy"><small>BANK FUNDED PROJECT</small><strong>산업화</strong><span>${escapeHtml(result.tile.name)} · 무료 랜드마크 건설</span></div><span class="bank-construction-crane" style="left:${startX}px;top:${startY}px;--crane-x:${targetX-startX}px;--crane-y:${targetY-startY}px"><i>🏦</i><b></b><em></em></span><span class="industrial-target-beacon" style="left:${target.left}px;top:${target.top}px;width:${target.width}px;height:${target.height}px"></span><div class="industrial-share-stamp"><b>80%</b><span>OWNER</span><i></i><b>20%</b><span>BANK</span></div>`;document.body.append(layer);requestAnimationFrame(()=>layer.classList.add('show'));
  if(!reducedMotion())await pause(820);await animateLandmarkConstruction({tileIndex:result.tile.index,tileName:result.tile.name,landmarkName:result.tile.landmarkName,landmarkGlyph:result.tile.landmarkGlyph,previousLevel:result.previousLevel,newLevel:result.newLevel},{industrial:true});layer.classList.add('complete');await pause(reducedMotion()?220:720);layer.remove();
}

export async function animateGenevaConvention(animation){
  document.querySelector('.geneva-convention-animation')?.remove();const island=document.querySelector('[data-tile-index="10"]');const released=Array.isArray(animation?.releasedPlayers)?animation.releasedPlayers:[];const rounds=Number(animation?.rounds)||2;const layer=document.createElement('div');layer.className='geneva-convention-animation';layer.setAttribute('role','status');layer.setAttribute('aria-label',`제네바 협정이 발동되어 ${rounds}라운드 동안 무인도 출입이 금지됩니다.`);layer.innerHTML=`<div class="geneva-treaty"><small>GENEVA CONVENTION</small><strong>제네바 협정</strong><p>무인도 출입 금지 · 갇힘 즉시 해제</p><div class="geneva-rounds">${Array.from({length:rounds},(_,index)=>`<i>${index+1} ROUND</i>`).join('')}</div><span class="geneva-seal">APPROVED<b>⚖</b></span></div>${released.length?`<div class="released-flight-list">${released.map((player,index)=>`<span style="--release-color:${player.color};--release-delay:${index*120}ms"><i>${escapeHtml(player.token||'✈')}</i><b>${escapeHtml(player.name)}</b><em>⛓</em><small>해방</small></span>`).join('')}</div>`:'<div class="released-flight-list empty"><span><i>✈</i><b>무인도 폐쇄</b><small>출입 차단</small></span></div>'}`;document.body.append(layer);
  let islandEffect=null;if(island){island.classList.add('geneva-sign-enter');islandEffect=document.createElement('span');islandEffect.className='geneva-island-animation';islandEffect.innerHTML=`<b>⛔</b><i>⛓</i><i>⛓</i><small>${rounds} ROUNDS CLOSED</small>`;island.append(islandEffect)}
  released.forEach(player=>{const token=document.querySelector(`[data-player-token="${player.id}"]`);if(!token||reducedMotion())return;token.animate([{transform:'translate(-50%,-50%) scale(1)',filter:'brightness(1)'},{transform:'translate(-50%,-85%) scale(1.35) rotate(-8deg)',filter:'brightness(1.9)',offset:.55},{transform:'translate(-50%,-50%) scale(1)',filter:'brightness(1)'}],{duration:1300,delay:760,easing:'cubic-bezier(.2,.8,.2,1)'})});requestAnimationFrame(()=>layer.classList.add('show'));await pause(reducedMotion()?700:2450);layer.remove();islandEffect?.remove();island?.classList.remove('geneva-sign-enter');
}

export async function animateIndustrialRentSplit(feedback){
  const split=feedback?.industrialSplit;if(!split||reducedMotion())return;const source=document.querySelector(`[data-player-mini="${split.payerId}"]`)?.getBoundingClientRect();const owner=document.querySelector(`[data-player-mini="${split.recipientId}"]`)?.getBoundingClientRect();const bank=document.querySelector('.bank-panel')?.getBoundingClientRect();if(!source||!owner)return;const originX=source.left+source.width/2;const originY=source.top+source.height/2;const ownerX=owner.left+owner.width/2;const ownerY=owner.top+owner.height/2;const bankX=bank?bank.left+bank.width/2:globalThis.innerWidth-42;const bankY=bank?bank.top+bank.height/2:globalThis.innerHeight*.78;
  const layer=document.createElement('div');layer.className='industrial-rent-split';layer.setAttribute('role','status');layer.setAttribute('aria-label',`산업화 통행료 중 소유주에게 ${formatMoney(split.ownerAmount)}, 은행에 ${formatMoney(split.bankAmount)}이 이동합니다.`);layer.innerHTML=`<span class="rent-split-origin" style="left:${originX}px;top:${originY}px">통행료 분배</span><span class="rent-share owner-share" style="left:${originX}px;top:${originY}px;--share-x:${ownerX-originX}px;--share-y:${ownerY-originY}px"><b>80%</b><small>${formatMoney(split.ownerAmount)}</small></span><span class="rent-share bank-share" style="left:${originX}px;top:${originY}px;--share-x:${bankX-originX}px;--share-y:${bankY-originY}px"><b>20%</b><small>${formatMoney(split.bankAmount)}</small></span>`;document.body.append(layer);await pause(1450);layer.remove();
}

export async function showMoneyFeedback(feedback){
  if(feedback?.gambler)return showGamblerResult(feedback.gambler);
  if(!feedback)return;document.querySelector('.money-feedback')?.remove();const element=document.createElement('div');element.className=`money-feedback tone-${feedback.tone||'info'}`;
  const sign=feedback.amount>0?'+':'−';element.innerHTML=`<small>${escapeHtml(feedback.title)}</small><strong>${sign}${formatMoney(Math.abs(feedback.amount))}</strong><span>${escapeHtml(feedback.message)}</span>`;document.body.append(element);
  element.setAttribute('role','status');requestAnimationFrame(()=>element.classList.add('show'));
  try{await Promise.all([pause(reducedMotion()?800:1300),feedback.industrialSplit?animateIndustrialRentSplit(feedback):animateMoneyTransfer(feedback.transfer)]);element.classList.remove('show');await pause(reducedMotion()?0:180)}finally{element.remove()}
}

const reducedMotion=()=>globalThis.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
const pause=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds));

export async function animateHalftimeAuction(result){
  if(reducedMotion())return;const center=document.querySelector('.board-center')?.getBoundingClientRect();if(!center||!result?.tiles?.length)return;const count=result.tiles.length;const middle=(count-1)/2;const spread=Math.min(18,120/Math.max(1,count-1));
  document.querySelector('.halftime-animation')?.remove();const layer=document.createElement('div');layer.className='halftime-animation';layer.setAttribute('role','status');layer.setAttribute('aria-label',`전반전이 끝나 남은 ${count}개 자산이 경매장으로 이동합니다.`);layer.innerHTML=`<div class="halftime-title"><small>FIRST HALF COMPLETE</small><strong>남은 ${count}개 자산</strong><span>경매장으로 이동합니다</span></div><div class="auction-vault"><i>♜</i><b>HALFTIME<br>AUCTION</b></div>`;
  result.tiles.forEach((summary,index)=>{const source=document.querySelector(`[data-tile-index="${Number(summary.index)}"]`)?.getBoundingClientRect();if(!source)return;const card=document.createElement('span');card.className='halftime-flying-card';card.style.left=`${source.left}px`;card.style.top=`${source.top}px`;card.style.width=`${source.width}px`;card.style.height=`${source.height}px`;card.style.setProperty('--fly-x',`${center.left+center.width/2-(source.left+source.width/2)}px`);card.style.setProperty('--fly-y',`${center.top+center.height/2-(source.top+source.height/2)}px`);card.style.setProperty('--fly-delay',`${Math.min(index,10)*60}ms`);card.style.setProperty('--land-x',`${(index-middle)*spread}px`);card.style.setProperty('--land-y',`${Math.abs(index-middle)*Math.min(4,20/Math.max(1,count-1))}px`);card.style.setProperty('--land-r',`${(index-middle)*-Math.min(4,28/Math.max(1,count-1))}deg`);card.innerHTML=`<i>${escapeHtml(summary.icon||'◆')}</i><b>${escapeHtml(summary.name)}</b>`;layer.append(card)});
  document.body.append(layer);requestAnimationFrame(()=>layer.classList.add('show'));await pause(1950);layer.remove();
}

export async function animateAuctionBid(result){
  if(reducedMotion())return;const source=document.querySelector(`[data-player-mini="${result?.bidder?.id}"]`)?.getBoundingClientRect();const target=document.querySelector('.auction-decision .decision-icon')?.getBoundingClientRect();if(!source||!target)return;
  const chip=document.createElement('div');chip.className='auction-bid-chip';chip.style.setProperty('--bidder-color',result.bidder.color);chip.textContent=formatMoney(result.amount);chip.style.left=`${source.left+source.width/2}px`;chip.style.top=`${source.top+source.height/2}px`;document.body.append(chip);const dx=target.left+target.width/2-(source.left+source.width/2);const dy=target.top+target.height/2-(source.top+source.height/2);
  try{await chip.animate([{opacity:0,transform:'translate(-50%,-50%) scale(.5) rotate(-10deg)'},{opacity:1,transform:'translate(-50%,-50%) scale(1.12) rotate(3deg)',offset:.25},{opacity:1,transform:`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px)) scale(.82) rotate(0)`}],{duration:720,easing:'cubic-bezier(.18,.8,.22,1)'}).finished}catch{}chip.remove();const panel=document.querySelector('.auction-decision');panel?.classList.add('bid-received');await pause(180);panel?.classList.remove('bid-received');
}

export async function animateAuctionAward(result){
  if(reducedMotion())return;document.querySelector('.auction-award-animation')?.remove();const layer=document.createElement('div');layer.className='auction-award-animation';layer.style.setProperty('--winner-color',result?.winner?.color||'#ffd95c');layer.setAttribute('role','status');layer.setAttribute('aria-label',`${result.winner.name}이 ${result.tile.name}을 낙찰받았습니다.`);layer.innerHTML=`<div class="award-hammer"><i>◆</i><b></b></div><small>SOLD!</small><strong>${escapeHtml(result.tile.name)}</strong><span>${escapeHtml(result.winner.name)} · ${formatMoney(result.amount)}</span>`;document.body.append(layer);requestAnimationFrame(()=>layer.classList.add('show'));
  const tile=document.querySelector(`[data-tile-index="${Number(result.tile.index)}"]`);tile?.style.setProperty('--winner-color',result.winner.color);tile?.classList.add('auction-won-flash');await pause(1350);tile?.classList.remove('auction-won-flash');layer.remove();
}

export async function animateSecondHalfStart(){
  if(reducedMotion())return;document.querySelector('.second-half-animation')?.remove();const layer=document.createElement('div');layer.className='second-half-animation';layer.setAttribute('role','status');layer.setAttribute('aria-label','후반전이 시작되어 자유 건설이 개방되었습니다.');layer.innerHTML='<div class="second-half-copy"><small>HALFTIME COMPLETE</small><strong>후반전 시작</strong><span>내 도시 자유 건설 개방</span></div><div class="construction-skyline"><i>▥</i><i>♜</i><i>▰</i><i>▥</i><i>♜</i></div><div class="construction-crane"><b></b><i></i></div>';document.body.append(layer);requestAnimationFrame(()=>layer.classList.add('show'));await pause(2050);layer.remove();
}

export async function animateRegionMonopoly(result){
  const tileElements=(result?.tiles||[]).map(summary=>({summary,element:document.querySelector(`[data-tile-index="${Number(summary.index)}"]`)})).filter(entry=>entry.element);if(!tileElements.length)return;document.querySelector('.region-monopoly-animation')?.remove();const meta=regionMeta(result.region);const centerRect=document.querySelector('.board-center')?.getBoundingClientRect();const centerX=centerRect?centerRect.left+centerRect.width/2:globalThis.innerWidth/2;const centerY=centerRect?centerRect.top+centerRect.height/2:globalThis.innerHeight/2;
  const layer=document.createElement('div');layer.className=`region-monopoly-animation${reducedMotion()?' reduced':''}`;layer.style.setProperty('--monopoly-color',meta.color);layer.setAttribute('role','status');layer.setAttribute('aria-label',`${result.player.name}이 ${meta.name} 지역을 독점했습니다. 해당 지역 통행료가 1.5배가 됩니다.`);layer.innerHTML=`<div class="monopoly-copy"><small>REGION MONOPOLY</small><strong>${escapeHtml(meta.name)} 독점!</strong><span style="--player:${result.player.color}"><i>${escapeHtml(result.player.token||'✈')}</i>${escapeHtml(result.player.name)} · 통행료 ×1.5</span></div><div class="monopoly-core" style="left:${centerX}px;top:${centerY}px"><i></i><b>♛</b></div>`;
  tileElements.forEach(({summary,element},index)=>{const rect=element.getBoundingClientRect();const tileX=rect.left+rect.width/2;const tileY=rect.top+rect.height/2;const dx=tileX-centerX;const dy=tileY-centerY;const line=document.createElement('i');line.className='monopoly-link';line.style.left=`${centerX}px`;line.style.top=`${centerY}px`;line.style.width=`${Math.hypot(dx,dy)}px`;line.style.setProperty('--link-angle',`${Math.atan2(dy,dx)*180/Math.PI}deg`);line.style.setProperty('--link-delay',`${index*70}ms`);layer.append(line);const seal=document.createElement('span');seal.className='monopoly-city-seal';seal.style.left=`${tileX}px`;seal.style.top=`${tileY}px`;seal.style.setProperty('--seal-delay',`${260+index*70}ms`);seal.innerHTML=`<i>✓</i><b>${escapeHtml(summary.name)}</b>`;layer.append(seal);element.style.setProperty('--monopoly-color',meta.color);element.style.setProperty('--monopoly-delay',`${index*70}ms`);element.classList.add('monopoly-tile-pulse')});
  document.body.append(layer);requestAnimationFrame(()=>layer.classList.add('show'));await pause(reducedMotion()?760:2150);layer.remove();tileElements.forEach(({element})=>{element.classList.remove('monopoly-tile-pulse');element.style.removeProperty('--monopoly-color');element.style.removeProperty('--monopoly-delay')});
}

export async function animateBankruptcy(result){
  if(!result?.player)return;document.querySelector('.bankruptcy-animation')?.remove();const destinationElement=(result.recipientId&&document.querySelector(`[data-player-mini="${result.recipientId}"]`))||document.querySelector('.bank-panel')||document.querySelector('.board-center');const destination=destinationElement?.getBoundingClientRect();const destinationX=destination?destination.left+destination.width/2:globalThis.innerWidth/2;const destinationY=destination?destination.top+destination.height/2:globalThis.innerHeight*.72;const layer=document.createElement('div');layer.className=`bankruptcy-animation${reducedMotion()?' reduced':''}`;layer.style.setProperty('--bankrupt-color',result.player.color||'#ff5d7d');layer.setAttribute('role','status');layer.setAttribute('aria-label',`${result.player.name}이 파산하여 현금이 0원이 되고 보유 자산이 회수됩니다.`);layer.innerHTML=`<div class="bankruptcy-copy"><small>INSOLVENT</small><strong>파산</strong><span><i>${escapeHtml(result.player.token||'✈')}</i>${escapeHtml(result.player.name)}</span><div class="bankruptcy-balance"><em>보유 현금</em><b>0원</b></div><p>${escapeHtml(result.reason||'지불 능력을 상실해 게임에서 제외되었습니다.')}</p></div><i class="bankruptcy-exit-plane">${escapeHtml(result.player.token||'✈')}</i>`;
  (result.assets||[]).forEach((asset,index)=>{if(!asset.rect)return;const rect=asset.rect;const ghost=document.createElement('span');ghost.className='bankruptcy-asset-ghost';ghost.style.left=`${rect.left}px`;ghost.style.top=`${rect.top}px`;ghost.style.width=`${rect.width}px`;ghost.style.height=`${rect.height}px`;ghost.style.setProperty('--reclaim-x',`${destinationX-(rect.left+rect.width/2)}px`);ghost.style.setProperty('--reclaim-y',`${destinationY-(rect.top+rect.height/2)}px`);ghost.style.setProperty('--reclaim-delay',`${Math.min(index,14)*55}ms`);ghost.innerHTML=`<i>${escapeHtml(asset.buildingLevel>0?(asset.landmarkGlyph||asset.icon):asset.icon||'◆')}</i><b>${escapeHtml(asset.name)}</b>`;layer.append(ghost)});
  const playerPanel=document.querySelector(`[data-player-mini="${result.player.id}"]`);playerPanel?.classList.add('bankruptcy-hit');document.body.append(layer);requestAnimationFrame(()=>layer.classList.add('show'));await pause(reducedMotion()?850:2450);layer.remove();playerPanel?.classList.remove('bankruptcy-hit');
}

export async function animateWorldCup(result){
  const tile=document.querySelector(`[data-tile-index="${Number(result?.tile?.index)}"]`);if(!tile)return;document.querySelector('.world-cup-animation')?.remove();const target=tile.getBoundingClientRect();const targetX=target.left+target.width/2;const targetY=target.top+target.height/2;const origin=document.querySelector('.board-center')?.getBoundingClientRect();const originX=origin?origin.left+origin.width/2:globalThis.innerWidth/2;const originY=origin?origin.top+origin.height/2:globalThis.innerHeight/2;const turns=Math.max(1,Number(result.turns)||3);
  const cupX=targetX-originX;const cupY=targetY-originY;const flashes=Array.from({length:18},(_,index)=>`<i style="left:${6+(index*23)%89}%;top:${12+(index*31)%72}%;--flash-delay:${(index%7)*90}ms"></i>`).join('');const layer=document.createElement('div');layer.className=`world-cup-animation${reducedMotion()?' reduced':''}`;layer.setAttribute('role','status');layer.setAttribute('aria-label',`${result.player?.name||'플레이어'}이 ${result.tile.name}에서 월드컵을 개최합니다. ${turns}번의 자기 차례 동안 통행료가 2배입니다.`);layer.innerHTML=`<div class="world-cup-lights"><i></i><i></i></div><div class="world-cup-flashes">${flashes}</div><div class="world-cup-copy"><small>WORLD CUP HOST CITY</small><strong>월드컵 개최!</strong><span>${escapeHtml(result.tile.name)} · 통행료 ×2 · ${turns}차례</span></div><span class="world-cup-ball" style="left:${originX}px;top:${originY}px;--cup-x:${cupX}px;--cup-y:${cupY}px;--cup-mid-x:${cupX*.68}px;--cup-mid-y:${cupY*.68-60}px">⚽</span><span class="world-cup-target" style="left:${target.left}px;top:${target.top}px;width:${target.width}px;height:${target.height}px"><i>×2</i></span>`;tile.classList.add('world-cup-celebration');document.body.append(layer);requestAnimationFrame(()=>layer.classList.add('show'));await pause(reducedMotion()?850:2250);layer.remove();tile.classList.remove('world-cup-celebration');
}
